typography_spectrum: 0.9809746991377324
color:
  brandStrength: 0.9801156504545361
  lightness: 0.5186519578564912
  saturation: 0.4613516505341977
  rhythmicContrast: 0.2739453837275505
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
layout_spectrum: 0.18074290128424764
author:
  name: Jenn LeBlanc
  email: jennkleblanc@gmail.com
  url: jennleblanc.com
name: Jenn LeBlanc
title: Jenn LeBlanc
description: erotic Victorian romance
